const mongoose = require('mongoose');

// Supported placeholder tokens mapped to user attributes
const SUPPORTED_PLACEHOLDERS = [
  '{{displayName}}', '{{firstName}}', '{{lastName}}', '{{jobTitle}}',
  '{{department}}', '{{company}}', '{{email}}', '{{phone}}',
  '{{mobilePhone}}', '{{businessPhone}}', '{{officeLocation}}',
  '{{streetAddress}}', '{{city}}', '{{state}}', '{{country}}',
  '{{website}}', '{{logoUrl}}', '{{bannerUrl}}', '{{bannerLink}}',
  '{{legalDisclaimer}}', '{{qrCodeUrl}}', '{{photoUrl}}',
];

const signatureTemplateSchema = new mongoose.Schema(
  {
    name: { type: String, required: true, trim: true },
    description: { type: String, default: '' },

    // Business unit this template belongs to
    businessUnit: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'BusinessUnit',
      required: true,
      index: true,
    },

    // Raw HTML with Handlebars-style placeholders
    htmlTemplate: {
      type: String,
      required: true,
    },

    // Plain text fallback
    plainTextTemplate: { type: String, default: '' },

    // Template layout type for UI categorization
    layout: {
      type: String,
      enum: ['standard', 'minimal', 'rich', 'two-column', 'custom'],
      default: 'standard',
    },

    // Which placeholders this template uses (auto-detected on save)
    usedPlaceholders: [{ type: String }],

    // Banner zone config
    hasBannerZone: { type: Boolean, default: false },
    hasQrCode: { type: Boolean, default: false },
    hasPhoto: { type: Boolean, default: false },

    // Language / locale
    locale: { type: String, default: 'en' },

    // Versioning
    version: { type: Number, default: 1 },
    isDefault: { type: Boolean, default: false },
    isActive: { type: Boolean, default: true },

    // Thumbnail preview (base64 or URL generated by preview service)
    previewUrl: { type: String, default: null },

    createdBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
    updatedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
  },
  { timestamps: true }
);

// Auto-detect placeholders used in the template before saving
signatureTemplateSchema.pre('save', function (next) {
  if (this.isModified('htmlTemplate')) {
    this.usedPlaceholders = SUPPORTED_PLACEHOLDERS.filter((p) =>
      this.htmlTemplate.includes(p)
    );
    this.version += this.isNew ? 0 : 1;
  }
  next();
});

// Only one default template per business unit
signatureTemplateSchema.pre('save', async function (next) {
  if (this.isModified('isDefault') && this.isDefault) {
    await this.constructor.updateMany(
      { businessUnit: this.businessUnit, _id: { $ne: this._id } },
      { $set: { isDefault: false } }
    );
  }
  next();
});

signatureTemplateSchema.index({ businessUnit: 1, isActive: 1 });
signatureTemplateSchema.index({ businessUnit: 1, isDefault: 1 });

module.exports = mongoose.model('SignatureTemplate', signatureTemplateSchema);
module.exports.SUPPORTED_PLACEHOLDERS = SUPPORTED_PLACEHOLDERS;
